### ISSUE TITLE
feature/comment

### ISSUE THREAD

**Issue by chaenabi** [we-are-dj/server#19]
주석 작업
@author
@created
@comment
등

**Comment by pursue503** [comment]
@chaenabi 
시큐리티 설정이 필터에 등록되는거까지 상세하게 작성했네요 
다른 부분도 확인해보니 크게 쓸건 더 없어보이는데
이부분만 수정하면 될거 같습니다.

PlayListException 클래스의 @author Charlie 이부분을 informix 로 변경해주시면 될거같네요

저녁에 집에가서 제가 작업한 부분도 이 브랜치에 커밋 하겠습니다.

**Comment by chaenabi** [comment]
@pursue503 
author 수정하였습니다.
검수 감사드립니다

**Comment by pursue503** [comment]
@chaenabi 작성 완료하였습니다.
