### ISSUE TITLE
feature/jwt

### ISSUE THREAD

**Issue by chaenabi** [we-are-dj/server#20]
jwt 기능 개발

**Comment by chaenabi** [comment]
jwt 인증 및 토큰 발급을 위한 정보로 사용하기 위하여
member entity에 member email과 member password 정보를 추가하였습니다.

**Comment by chaenabi** [comment]
test code는 미완성이며 아직 테스트 성공한 적이 없습니다.

**Comment by chaenabi** [comment]
jwt 생성을 위한 email, password 정보를 제거하고 카카오 oauth2 통신 로직으로 대체하였습니다.

**Comment by pursue503** [comment]
@chaenabi 이 이슈는 완료 했으니 닫겠습니다.
