### ISSUE TITLE
Modify Member NickName

### ISSUE THREAD

**Issue by pursue503** [we-are-dj/server#46]
### 👋 작업 내용
회원 닉네임 변경 API 를 제작합니다.

### ⚙️ 진행 방식
1. 닉네임 중복 체크 (중복 불가능)
2. 중복시 에러 던져주기
3. 중복 아닐시 변경성공 변경값 전송
4. Swagger 를 이용하여 API 설명 작성

### 🎇 기대 결과

회원 닉네임 변경 API 제작 완료

**Comment by chaenabi** [comment]
로그인 중인 회원이 닉네임 변경 요청했을때 처리하는 로직 구현됨

**Comment by chaenabi** [comment]
신규 로그인하는 유저의 닉네임을 카카오 프로필의 닉네임 그대로 가져와 저장하던 로직에서,
닉네임_숫자 으로 저장하도록 로직을 변경하여 중복을 제거하는 목표 달성

**Comment by chaenabi** [comment]
기능 구현이 완료되었으므로 이슈를 닫습니다.
