### ISSUE TITLE
feature/chat

### ISSUE THREAD

**Issue by chaenabi** [we-are-dj/server#64]
### 👋 작업 내용
실시간 채팅을 구현합니다.

### ⚙️ 진행 방식

- use springboot's redis auto configuration 

redis를 선택한 이유
1. 설정이 편함
2. 전송속도가 빠름
3. 푸시 기반이므로 메시지가 대기열에 있으면
   사용자에게 바로 푸시되기 때문에 따로 사용자가 메시지를 요청할 필요가 없음.

redis를 선택하며 포기한 점
1. 안정성 (카프카에 비해 상대적인 메시지 소실 위험이 있음)
2. 원활한 대용량 트래픽 연산 (+ 참여자가 많을 경우 성능에 악영향이 있음)
3. 인메모리방식이므로 일반적인 사용법으로는 채팅기록을 남길 수 없음

### 🎇 기대 결과
실시간 채팅방 서비스가 제공됩니다.

**Comment by pursue503** [comment]
채팅은 구현하였습니다 새롭게 room API 작업 이슈를 엽니다.
