### ISSUE TITLE
feature/ModifyMusicList

### ISSUE THREAD

**Issue by pursue503** [we-are-dj/server#65]
### 👋 작업 내용
1. 재생목록의 노래 순서를 변경합니다.

### ⚙️ 진행 방식
노래 순서 변경은 프론트에서 드래그앤 드랍으로 노래 위치를 변경후
서버로 데이터를 보냅니다.

서버는 데이터를 List 형태로 받고

Update를 시켜줍니다.

### 🎇 기대 결과

1. 재생목록 변경 API가 완성됩니다.

**Comment by chaenabi** [comment]
음악 변경 로직 구현을 완료했습니다. 풀 리퀘스트를 진행합니다.

**Comment by chaenabi** [comment]
풀리퀘스트를 병합했으므로 이슈를 닫습니다.
