### ISSUE TITLE
CustomExceptionRefactoring

### ISSUE THREAD

**Issue by pursue503** [we-are-dj/server#66]
### 👋 이슈 내용

기존에 있던 각 도메인별 Exception을 
하나의 공통 BizException 으로 통일합니다.

### 🎇 기대 결과
서비스가 커지면 많아지는 클래스의 양을 줄일수 있습니다.

**Comment by chaenabi** [comment]
상위 브랜치에 머지했으므로 이슈를 닫습니다.
