### ISSUE TITLE
MusicRoom Create Limit Http Error Code

### ISSUE THREAD

**Issue by pursue503** [we-are-dj/server#72]
### 👋 이슈 내용
방 생성 제한에 대한 HttpStatusCode 조언

MusicRoom 에 대하여 1인당 5개의 방까지 만들 수 있도록 제한을 두려합니다.

현재 final로 선언이 되어있는 상태이며

나중에 DB로 전환할예정입니다

```java
    private final static int CHAT_ROOM_LIMIT = 5;
if(musicRoomRepository.countByRoomMaster(member) >= CHAT_ROOM_LIMIT) throw new BizException(RoomCrudErrorCode.BAD_REQUEST);
```

현재 400번의 에러 BAD_REQUEST 로 상태코드와 에러메세지를 보내주고 있는데

400번 말고 적절한 상태코드가 있을지 조언 부탁드립니다.

**Comment by chaenabi** [comment]
403 Forbidden이 적절해보입니다.

https://stackoverflow.com/questions/39221380/what-is-the-http-status-code-for-license-limit-reached

**Comment by pursue503** [comment]
422 code로 지정하겠습니다.
