### ISSUE TITLE
개발용) JWT Interceptor Pass Token 

### ISSUE THREAD

**Issue by pursue503** [we-are-dj/server#86]
### 👋 작업 내용
개발용으로 Header 에 특정 값을 심어서 보내면 토큰 검증 인터셉터를 통과하고
개발용 MemberId 값을 가져와서 값을 추가해주는 기능 필요

### ⚙️ 진행 방식
1. JWT 인터셉터에서 우선적으로 해당 개발용 Header 값이 있는지 확인 ( 개발용 Header 값은 DB에 저장후 불러오기 ) 존재하면 인터셉터 통과
2. 상수값용 테이블 생성 table 명 properties

```
CREATE TABLE properties
(
    `prop_key`      INT             NOT NULL    COMMENT '키값', 
    `prop_value`    VARCHAR(100)    NULL        COMMENT '값', 
    `prop_content`  VARCHAR(70)     NULL        COMMENT '설명', 
    CONSTRAINT PK_properties PRIMARY KEY (prop_key)
);
```

3. properties Entity , Repository 생성

ex) insert into properties values('dev_token', 'abc1234', '개발용 토큰 상수값');

4. 개발용 Member 데이터 생성

### 🎇 기대 결과

1. 프론트가 개발 하는데 매번 로그인 할 필요없이 특정값만 보내줘도 API를 이용할 수 있습니다
2. 프론트 개발이 편해집니다.

추가로 이해가 안되는 부분은 comment 남겨주세요

**Comment by chaenabi** [comment]
fix bug: formatting LocalDateTime json  by ErrorResponseDTO 
from 
"timestamp":"[2021, 09, 17, ... ]"
to
"timestamp":"2021-09-17T10:37:50.586"

**Comment by pursue503** [comment]
회원 더미데이터 ID값 34~54 생성 완료.
